chore: update dependencies (#2316)
In particular for:
```
Crate:         openssl-src
Version:       111.20.0+1.1.1o
Title:         AES OCB fails to encrypt some bytes
Date:          2022-07-05
ID:            RUSTSEC-2022-0032
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0032
error: 1 vulnerability found!
Solution:      Upgrade to >=111.22, <300.0 OR >=300.0.9
```