refactor: Identity::wallet_canister_id returns DfxResult<Option<Principal>> (#2385)
# Description

If there's no `wallets.json` file, or if `wallets.json` doesn't have a wallet id for a given identity/network, this isn't an error.  It instead means there's no wallet for that identity on that network.

Actual errors could be things like permissions errors, or malformed json.

This PR changes `Identity::wallet_canister_id` to return `DfxResult<Option<Principal>>`.

As can be seen in the PR, most callers discard any error details and assume that any error means that there was no wallet.  But we should report things like permissions problems or malformed errors as errors.

# How Has This Been Tested?

Added an e2e test.

before
```
$ dfx --identity alice wallet upgrade
Error: Failed to get wallet canister id for identity 'alice' on network 'local'.
Caused by: Failed to get wallet canister id for identity 'alice' on network 'local'.
  Could not find wallet for "alice" on "local" network.
```

after
```
$ dfx --identity alice wallet upgrade
Error: There is no wallet defined for identity 'alice' on network 'local'.  Nothing to do.
```

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] (n/a) I have made corresponding changes to the documentation.