fix: HSM support on Linux build (#2202)
# Description

Build the Linux binary dynamically, as was done in dfx 0.9.3 and earlier, in order to avoid the following error when trying to use an HSM:
```
Error: IO: Dynamic loading not supported
```

Other changes to the workflow:
- manually build a static-linked openssl for the linux build
- allow words other than "beta" in the tag name
- removed the "test-#.#.#-*" tag allowance, because those wouldn't be a valid semver (and dfx would panic)
- verify the list of referenced dynamic libraries, to avoid post-release surprises.

Fixes https://dfinity.atlassian.net/browse/SDK-495 

# How Has This Been Tested?

Tested manually with an HSM.  Here's a sample release: https://github.com/dfinity/sdk/releases/tag/0.10.1-hsm.1

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] (n/a) I have made corresponding changes to the documentation.