refactor: IdentityManager::create_new_identity
Tested with:

dfx identity new forced --force
set breakpoint
dfx identity use forced
set breakpoint
dfx identity new forced --force
chmod u-w ~/.config/dfx/identity.json
continue

Error: Failed to switch back over to the identity you're replacing. Please run 'dfx identity use forced' to do it manually.
Caused by: Failed to switch back over to the identity you're replacing. Please run 'dfx identity use forced' to do it manually.
  Failed to save identity manager configuration: Failed to write JSON file: Failed to write to /Users/ericswanson/.config/dfx/identity.json: Permission denied (os error 13)