feat: support canisters and principals in dfx ledger account-id
This change adds new capabilities to the `dfx ledger account-id`
command:

  * The `--subaccount` option allows you to get an account id for a
    subaccount other than the default one.

  * The `--of-principal` option allows you to specify the controller
    of the subaccount to compute addresses that your identity doesn't
    control.

  * The `--of-canister` option allows you to specify canister alias
    instead of the principal.

Examples:

```sh
$ dfx ledger account-id --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai
e9b0cdfcb858f5538d0d1d8d0a2700ccda299451c88bf686d00a3d8fb74dcfea

$ dfx ledger --network small02 account-id --of-canister ledger_demo
e9b0cdfcb858f5538d0d1d8d0a2700ccda299451c88bf686d00a3d8fb74dcfea

$ dfx ledger account-id \
  --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai \
  --subaccount 0000000000000000000000000000000000000000000000000000000000000001
adddf401b1936409217493ed02b144ede539c6397c270b4ca8069f9930a4f4c9
```

This change also improves the error reporting by displaying error
causes if there are any. Example:

```sh
$ dfx ledger account-id \
  --of-principal 53zcu-tiaaa-aaaaa-qaaba-cai \
  --subaccount 00000000000000000000000000000000000000000000000000000000000000000
Error: Subaccount '00000000000000000000000000000000000000000000000000000000000000000' is not a valid hex string
Caused by:
  Odd number of digits
```

Fixes #1981.