fix: statically link openssl into icx-proxy (#1760)
Even though this passed CI, it can't be merged, because `nix-shell` fails locally:

```
          ld: warning: object file (/private/var/folders/vl/2fdfs_116pb82rzcb_s779d80000gn/T/nix-build-agent-rs-unknown.drv-0/source/target/release/deps/libopenssl_sys-d40904efb13332ca.rlib(cms_dd.o)) was built for newer OSX version (10.15) than being linked (10.12)
          ld: warning: object file (/private/var/folders/vl/2fdfs_116pb82rzcb_s779d80000gn/T/nix-build-agent-rs-unknown.drv-0/source/target/release/deps/libopenssl_sys-d40904efb13332ca.rlib(wp-x86_64.o)) was built for newer OSX version (10.15) than being linked (10.12)
          ld: warning: object file (/private/var/folders/vl/2fdfs_116pb82rzcb_s779d80000gn/T/nix-build-agent-rs-unknown.drv-0/source/target/release/deps/libopenssl_sys-d40904efb13332ca.rlib(bio_asn1.o)) was built for newer OSX version (10.15) than being linked (10.12)
          ld: warning: object file (/private/var/folders/vl/2fdfs_116pb82rzcb_s779d80000gn/T/nix-build-agent-rs-unknown.drv-0/source/target/release/deps/libopenssl_sys-d40904efb13332ca.rlib(bio_b64.o)) was built for newer OSX version (10.15) than being linked (10.12)
          Undefined symbols for architecture x86_64:
            "____chkstk_darwin", referenced from:
                _BN_mod_exp_mont_consttime in libopenssl_sys-d40904efb13332ca.rlib(bn_exp.o)
                _RSAZ_1024_mod_exp_avx2 in libopenssl_sys-d40904efb13332ca.rlib(rsaz_exp.o)
                _curve448_base_double_scalarmul_non_secret in libopenssl_sys-d40904efb13332ca.rlib(curve448.o)
                _ERR_print_errors_cb in libopenssl_sys-d40904efb13332ca.rlib(err_prn.o)
          ld: symbol(s) not found for architecture x86_64
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
          
```