chore: updates webpack dependencies (#2264)
# Description

Resolves an issue with running `npm start` in a fresh project, leading to the message 
```
TypeError: cli.isMultipleCompiler is not a function 
```

Fixes SDK-541

# How Has This Been Tested?

Run locally with a new project

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] I have made corresponding changes to the documentation.