chore: Update dependencies (#2067)
Updates most dependencies reported by `cargo outdated -R`

Fixes this cargo audit failure seen here https://github.com/dfinity/sdk/pull/2065 :
```
    Avoids this cargo audit failure:
    
    Crate:         regex
    Version:       1.5.4
    Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
    error: 1 vulnerability found!
    Date:          2022-03-08
    ID:            RUSTSEC-2022-0013
    URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
    Solution:      Upgrade to >=1.5.5

```