fix: Nix eval error due to fetchGit only supporting revisions
The following used to work:

```
nix-repl> builtins.fetchGit { url = "ssh://git@github.com/dfinity-lab/agent-rust"; ref = "v0.6.3"; }
{ outPath = "/nix/store/rrlmgrf9z0nm9jzbimbsl6rpj96ij9yn-source"; rev = "5b2fab20e1902f8709d1b09fcb6f5ee9feb0084e"; revCount = 42; shortRev = "5b2fab2"; }
```

However, due to a Nix upgrade on Hydra this doesn't seem to work
anymore:

```
nix-repl> builtins.fetchGit { url = "ssh://git@github.com/dfinity-lab/agent-rust.git"; ref = "v0.6.3"; }
fetching Git repository 'ssh://git@github.com/dfinity-lab/agent-rust.git'fatal: couldn't find remote ref refs/heads/v0.6.3
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
program 'git' failed with exit code 128
```

I'm not sure this is intended behaviour but it could be that Nix wants
to have a revision in order to guarantee that the source doesn't
change:

```
nix-repl> builtins.fetchGit { url = "ssh://git@github.com/dfinity-lab/agent-rust"; rev = "5b2fab20e1902f8709d1b09fcb6f5ee9feb0084e"; ref = "0.6"; }
{ lastModified = 1596813025; lastModifiedDate = "20200807151025"; narHash = "sha256-LJY3PJeTFaR3nn0/SAxbAOhogkcQS3JkHUiyOY14lWA="; outPath = "/nix/store/rrlmgrf9z0nm9jzbimbsl6rpj96ij9yn-source"; rev = "5b2fab20e1902f8709d1b09fcb6f5ee9feb0084e"; revCount = 42; shortRev = "5b2fab2"; submodules = false; }
```

Note that if the revision is not reachable from `master` it's also
required to specify a branch. Unfortunately this does currently raise
a warning in cargo:

```
$ cargo build
warning: /Users/bas/d/sdk/hansl/move-ic-agent-to-own-repo/src/ic_identity_manager/Cargo.toml: dependency (ic-agent) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
warning: /Users/bas/d/sdk/hansl/move-ic-agent-to-own-repo/src/dfx/Cargo.toml: dependency (ic-agent) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
```