feat: look up running webserver port (#2301)
# Description

If `--host <addr>:0` is passed to `dfx start`, the dfx (icx-proxy) webserver will listen on an ephemeral port.  However, dfx will not connect to the running server unless dfx.json is first modified to reflect the dynamically-allocated port.

This shows up in the e2e test suite: after `dfx start`, the setup functions alter dfx.json.  Reviewers can see this in `_.bash`, which no longer alters dfx.json after `dfx start`.

In the upcoming system-wide dfx server changes, in many (if not most) cases there will not be a `local` network entry in dfx.json (project or shared) at all.  This means that tests would have to add a local network entry, which would change the conditions of the test.

`dfx start` also stores the port of the running webserver port in `.dfx/webserver-port`.  This PR makes dfx use this port if it is present in this file.

Before
```
$ dfx start --background --host 127.0.0.1:0
...
 Jun 28 20:31:11.687 INFO Starting server. Listening on http://127.0.0.1:56492/
$ dfx ping
Error: Failed while waiting for agent status.
Caused by: Failed while waiting for agent status.
  An error happened during communication with the replica: error sending request for url (http://127.0.0.1:8000/api/v2/status): error trying to connect: tcp connect error: Connection refused (os error 61)
```
After
```
$ dfx start --background --host 127.0.0.1:0
...
 Jun 28 20:34:03.216 INFO Starting server. Listening on http://127.0.0.1:56532/
$ dfx ping
{
  "ic_api_version": "0.18.0"  "impl_hash": "c01380c5c40891089bf295c7bc91ab157a9b8fff0417415239b54037d6211ab8"  "impl_version": "0.8.0"  "replica_health_status": "healthy"  "root_key": [48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 180, 206, 190, 177, 185, 147, 165, 78, 12, 208, 18, 119, 8, 66, 132, 236, 216, 108, 190, 216, 85, 33, 212, 189, 232, 225, 32, 34, 234, 3, 107, 114, 199, 222, 88, 36, 207, 179, 18, 247, 163, 58, 187, 114, 95, 237, 96, 83, 11, 243, 212, 39, 65, 107, 123, 73, 44, 248, 98, 24, 99, 39, 237, 202, 80, 163, 172, 163, 224, 137, 108, 82, 126, 255, 144, 125, 6, 243, 59, 47, 84, 194, 130, 114, 73, 224, 93, 38, 219, 136, 217, 248, 251, 104, 163, 222]
```

# How Has This Been Tested?

Covered by e2e tests and new unit tests.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] (n/a) I have made corresponding changes to the documentation.