fix: dfx start should detect if dfx is already running (#2134)
# Description

While writing other tests, I noticed that `dfx start` outputs "Address already in use" instead of "dfx is already running" if dfx is already running.

It turned out that dfx start wasn't actually checking the process list, because the newer version of `system` that we're using requires a call to update the process list.

Worse, it would overwrite `.dfx/pid` with an empty file, then fail with `Address is already in use`, meaning `dfx stop` would later not know which pid to signal.

Fixes # https://dfinity.atlassian.net/browse/SDK-424

# How Has This Been Tested?

Added an e2e test.

Before
```
$ dfx start --background && dfx start
...

Apr 18 10:19:32.478 INFO Starting server. Listening on http://127.0.0.1:8000/
Error: Address already in use (os error 48)
$ dfx stop
$ dfx start
Error: Address already in use (os error 48)
```

After
```
$ dfx start --background && dfx start
...
Apr 18 10:24:06.743 INFO Starting server. Listening on http://127.0.0.1:8000/
Error: dfx is already running.
$ dfx stop
Apr 18 17:24:33.285 INFO Caught SIGTERM
Stopping the replica...
Stopped.                                                                                                                                                                                                     
Stopping icx-proxy...
Stopped.
$ dfx start
...
 Apr 18 10:26:02.361 INFO Starting server. Listening on http://127.0.0.1:8000/
```


# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] (not needed) I have made corresponding changes to the documentation.