ci: update lazy-init to 0.5.0 (#1303)
This attempts to fix the failing[ cargo audit job](https://hydra.dfinity.systems/build/2904578) by updating `lazy-init` to `0.5.0`
```
error: Vulnerable crates found!

ID:       RUSTSEC-2021-0004
Crate:    lazy-init
Version:  0.3.0
Date:     2021-01-17
URL:      https://rustsec.org/advisories/RUSTSEC-2021-0004
Title:    Missing Send bound for Lazy
Solution:  upgrade to > 0.4.0
Dependency tree:
lazy-init 0.3.0
└── dfx 0.6.18

```