refactor: make temp dir optional (#2401)
# Description

This PR renames `Environment::get_temp_dir()` to `get_project_temp_dir()`.  It returns either the `.dfx/` directory in the same directory as `dfx.json`, or None if there is no project.

`Environment::get_temp_dir()` is only used in two places:
- when looking up the wallet id for a network with ephemeral canister ids, which only makes sense within a project directory
- when renaming an identity, which already allows for the wallet configuration file to not exist

This also means that dfx no longer creates a temporary directory if run outside of a project directory.  These temporary directories were never cleaned up.  It would never make sense to write or read a wallets.json file within such a temporary directory.

before
```
$ dfx wallet upgrade
dfx.json not found, using default.
Error: Failed to get wallet canister id for identity 'default' on network 'local'.
Caused by: Failed to get wallet canister id for identity 'default' on network 'local'.
  Failed to find wallet file /var/folders/7l/6w8kktld2xn8qfz_m84bx18c0000gn/T/.tmpgCtaaH/local/wallets.json.
```

after
```
$ dfx-wip wallet upgrade
dfx.json not found, using default.
Error: Failed to get wallet canister id for identity 'default' on network 'local'.
Caused by: Failed to get wallet canister id for identity 'default' on network 'local'.
  Failed to get path to wallet config file for identity 'default' on network 'local'.
    It's only possible to interact with a wallet for a local network from a project directory.
```

# How Has This Been Tested?

Added an e2e test.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] (n/a) I have made corresponding changes to the documentation.